
//Use strict states the code should only be ran in strict mode.
//Meaning the use of undeclared variables is not permitted
'use strict';


//installing all dependencies
//fs known for file system and is used to read write and create files
var fs        = require('fs');
// path dependency is used to work with directory and file paths
var path      = require('path');
//importing sequalize npm package functionality
var Sequelize = require('sequelize');
//return the filename path
var basename  = path.basename(module.filename);
//when launching a server, the server will detect what server to run the server.js file from. Here we are
//specifying the devcelopment node environment OR any environment
var env       = process.env.NODE_ENV || 'development';
//importing config files and script
var config    = require(__dirname + '/../config/config.json')[env];
//cerating an empty databse object
var db        = {};
//this is generated by the sequalize CLI when you run a sequalize init model
//this creats a config environment this is helpful during uploading to heroku
if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}
//==================================================================
//reading files synchronously 
//here we are reving all the files within the models folder that have the extension of .js 
//and importing them into the config environment

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(function(file) {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });
//==================================================================

//==================================================================
//We are associating all the functions forEach model script file using .associate
//associating functions to modles
Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});
//the creation of our own sequalize database
db.sequelize = sequelize;
//the general Sequalize library
db.Sequelize = Sequelize;
//==================================================================
//exporting the index model
module.exports = db;
